services:
  web:
    build:
      context: ../../
      dockerfile: operation/Docker/dockerfile
    ports:
      - "3000:3000"
    image: kausheekraj/trendstore-nginx:latest
    container_name: Trend-store
