apiVersion: v1
kind: Service
metadata:
  name: trendstore-service
spec:
  type: NodePort
  selector:
    app: trendstore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
